const navLinks = document.querySelectorAll('.nav-link');

navLinks.forEach(link => {
  link.addEventListener('click', event => {
    event.preventDefault();
    const sectionId = link.getAttribute('href');
    document.querySelector(sectionId).scrollIntoView({ behavior: 'smooth' });
  });
});

window.addEventListener('scroll', () => {
  const sections = document.querySelectorAll('section');
  const navItems = navLinks;
  const currentScrollPos = window.pageYOffset;

  sections.forEach(section => {
    if (
      section.offsetTop <= currentScrollPos &&
      section.offsetTop + section.offsetHeight > currentScrollPos
    ) {
      navItems.forEach(link => {
        link.classList.remove('active');
        if (section.getAttribute('id') === link.getAttribute('href')) {
          link.classList.add('active');
        }
      });
    }
  });
});



(() => {
//If you want to add more images, add the link name and URL image URL in the array list below.
	const images_list = [
{
    "url": "https://html-generator.com/uploads/images/2023/06/07/54304ODYHX8ZDJ5.png",
    "alt": "",
    "name": "54304ODYHX8ZDJ5.png",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/06/07/56223TQVK_92RZ_.png",
    "alt": "",
    "name": "56223TQVK_92RZ_.png",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/06/07/57656MAIJH18GR_.png",
    "alt": "",
    "name": "57656MAIJH18GR_.png",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/06/07/5921153Q8T9OC7M.png",
    "alt": "",
    "name": "5921153Q8T9OC7M.png",
    "link": ""
}
	];

// generated by https://www.html-code-generator.com/html/image-slideshow-generator
	let slider_id = document.querySelector("#hcg-slider-1");

	// append all images
	let dots_div = "";
	let images_div = "";
	for (let i = 0; i < images_list.length; i++) {
		// if no link without href="" tag
		let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
		images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
						'<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
						'<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
					 '</a>';
	}
	slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
	let slide_index = 0;

	const images = slider_id.querySelectorAll(".hcg-slides");
	const prev_button = slider_id.querySelector("#hcg-slide-prev");
	const next_button = slider_id.querySelector("#hcg-slide-next");

	const showSlides = () => {
		if (slide_index > images.length-1) {
			slide_index = 0;
		}
		if (slide_index < 0) {
			slide_index = images.length-1;
		}
		for (let i = 0; i < images.length; i++) {
			images[i].style.display = "none";
			if (i == slide_index) {
				images[i].style.display = "flex";
			}
		}
	}

	prev_button.addEventListener("click", event => {
		event.preventDefault();
		slide_index--;
		showSlides();
	}, false);

	next_button.addEventListener("click", event => {
		event.preventDefault();
		slide_index++;
		showSlides();
	}, false);

})();

